name: Update Release and Upload Zip

on:
  push:
    branches: ['fullscreen_rework']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      tag: fullscreen
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Edit Release
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          const tag = "${{env.tag}}";
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          
          const releases = await github.rest.repos.listReleases({
            owner,
            repo,
          });

          const release = releases.data.find((release) => release.tag_name === tag);

          console.log(release.data);

          if(!release) {
            console.log(`Release with tag ${tag} not found`);
            return;
          }
          
          const body = fs.readFileSync('readme.md', 'utf8');

          await github.rest.repos.updateRelease({
            owner,
            repo,
            release_id: release.data.id,
            body,
          });
    - name: Zip the repository
      run: |
        mkdir PlayniteWatcher
        mv . PlayniteWatcher
        zip -r PlayniteWatcher.zip PlayniteWatcher

    - name: Upload zip to the release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: https://github.com/${{ github.repository }}/releases/tag/{{env.tag}}
        asset_path: ./${{ github.repository }}.zip
        asset_name: ${{ github.repository }}.zip
        asset_content_type: application/zip

    - name: Force update the tag
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          await github.git.updateRef({
            owner,
            repo,
            ref: `tags/${{env.tag}}`,
            sha: context.sha,
            force: true
          });
